name: Deploy CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    # æœåŠ¡å™¨ç¯å¢ƒ
    runs-on: ubuntu-latest

    steps:
      - name: checkout ğŸ›ï¸
        uses: actions/checkout@master

      - name: install ğŸ“¦
        run: yarn install

      - name: build ğŸ”§
        run: yarn run docs:build

      - name: deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
